# Generated by Django 3.1 on 2020-08-17 09:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice', models.FileField(upload_to='')),
                ('title', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.CharField(choices=[('First', 'First'), ('Second', 'Second'), ('Third', 'Third'), ('Fourth', 'Fourth')], max_length=50, null=True)),
                ('no', models.CharField(max_length=5)),
                ('room_type', models.CharField(choices=[('S', 'Single Occupancy'), ('D', 'Double Occupancy'), ('T', 'Triple Occupancy')], default=None, max_length=1)),
                ('capacity', models.IntegerField(default=None)),
                ('vacant', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, default='profilepic.png', null=True, upload_to='')),
                ('fee_receipt', models.FileField(default='', upload_to='')),
                ('student_name', models.CharField(max_length=200, null=True)),
                ('student_mail', models.CharField(max_length=200, null=True)),
                ('student_contact', models.IntegerField(null=True)),
                ('father_name', models.CharField(max_length=200, null=True)),
                ('enrollment_no', models.IntegerField(null=True, unique=True)),
                ('course', models.CharField(choices=[('BTECH', 'BTECH'), ('MCA', 'MCA'), ('MBA', 'MBA'), ('MTECH', 'MTECH')], max_length=50, null=True)),
                ('student_address', models.CharField(max_length=200, null=True)),
                ('dob', models.DateField(help_text='format : YYYY-MM-DD', max_length=10, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default=None, max_length=1, null=True)),
                ('curr_year', models.CharField(choices=[('First', 'First'), ('Second', 'Second'), ('Third', 'Third'), ('Fourth', 'Fourth')], max_length=50, null=True)),
                ('room', models.IntegerField(null=True)),
                ('room_allotted', models.BooleanField(default=False)),
                ('no_dues', models.BooleanField(default=True)),
                ('user', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
